<?php
/**
 * ResourceSpace Configuration Overrides
 * 
 * This file contains custom configuration for the ResourceSpace installation.
 * Values here override defaults from config.default.php
 * 
 * Database settings are read from environment variables.
 * Security keys are auto-generated by RS during setup.
 * 
 * For full configuration options, see:
 * https://www.resourcespace.com/knowledge-base/systemadmin/config_file
 */

// =============================================================================
// Database Configuration (from environment variables)
// =============================================================================
$mysql_server = getenv('DB_HOST') ?: 'mariadb';
$mysql_username = getenv('DB_USER') ?: 'resourcespace_rw';
$mysql_password = getenv('DB_PASSWORD') ?: '';
$mysql_db = getenv('DB_NAME') ?: 'resourcespace';

// Azure MySQL SSL (uncomment if using Azure MySQL with SSL)
// $mysql_ssl_ca_path = '/etc/ssl/certs/DigiCertGlobalRootCA.crt.pem';

// =============================================================================
// General Settings (optional - can be set during setup)
// =============================================================================
if (getenv('RS_BASE_URL')) {
    $baseurl = getenv('RS_BASE_URL');
}

if (getenv('RS_APP_NAME')) {
    $applicationname = getenv('RS_APP_NAME');
}

// =============================================================================
// Storage Settings
// =============================================================================
$storagedir = '/var/www/html/filestore';

// =============================================================================
// Security Settings
// =============================================================================
// These are AUTO-GENERATED by ResourceSpace during initial setup.
// Only set via env vars if you need to override (e.g., migrating existing install)
if (getenv('RS_SCRAMBLE_KEY')) {
    $scramble_key = getenv('RS_SCRAMBLE_KEY');
}

if (getenv('RS_API_SCRAMBLE_KEY')) {
    $api_scramble_key = getenv('RS_API_SCRAMBLE_KEY');
}

// =============================================================================
// Email Settings (optional)
// =============================================================================
if (getenv('RS_EMAIL_FROM')) {
    $email_from = getenv('RS_EMAIL_FROM');
}

if (getenv('RS_EMAIL_NOTIFY')) {
    $email_notify = getenv('RS_EMAIL_NOTIFY');
}
